version: '3.8'

services:
  web:
    build: ./website
    volumes:
      - ./website/:/usr/src/website
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
