version: '3.8'

services:
  web:
    build: ./website
    volumes:
      - ./website/:/usr/src/website
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  # djnago-api:
  #   build: ./website
  #   volumes:
  #     - ./website/:/usr/src/website
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  #   depends_on:
  #     - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin/data/
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    depends_on:
      - db
  node:
    build: ./react-web
    container_name: react-web
    restart: always
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - web
    volumes:
      - ./react-web/public:/usr/src/react-web/public
      - ./react-web/src:/usr/src/react-web/src

volumes:
  postgres_data:
  pgadmindata:
