# Generated by Django 4.2.1 on 2023-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_background.jpg', upload_to='product_images')),
                ('category', models.CharField(max_length=50)),
                ('size', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
